import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className='px-[1rem] my-[2.5rem]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

    </div>
  )
}
